"""ada lagi yang harus disesuikan

Revision ID: 2e79d27ce3d9
Revises: 5991714953dd
Create Date: 2025-09-14 20:12:14.750652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e79d27ce3d9'
down_revision = '5991714953dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_column('perawat')
        batch_op.drop_column('jabatan')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jabatan', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('perawat', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
