"""harusnya sudah mau jadi

Revision ID: 425f136d6073
Revises: daf92737fe35
Create Date: 2025-09-29 13:38:23.448922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '425f136d6073'
down_revision = 'daf92737fe35'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervensi_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'intervensi', ['intervensi_id'], ['id'])
        
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervensi_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'intervensi', ['intervensi_id'], ['id'])


    # ### end Alembic commands ##


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'user', 'editor', name='roleenum', schema='public'),
               type_=postgresql.ENUM('admin', 'user', 'editor', name='roleenum'),
               nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assesment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('patients_assesment_id_fkey'), 'assesments', ['assesment_id'], ['id'])

    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('laporan_cppt_id_fkey'), 'CPPT', ['cppt_id'], ['id'])
        batch_op.drop_column('intervensi_id')

    with op.batch_alter_table('assesments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=True))

    op.create_table('CPPT',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tanggal', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('jabatan', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('subjective', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objective', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assessment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keterangan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dokter', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('CPPT_patient_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('CPPT_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('CPPT_pkey'))
    )
    op.drop_table('cppt')
    # ### end Alembic commands ###
