"""perubahan strukut sdki pada tabel cppt

Revision ID: 4f2874a40629
Revises: 2e79d27ce3d9
Create Date: 2025-09-18 15:20:13.160075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2874a40629'
down_revision = '2e79d27ce3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SDKI', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_column('SDKI')

    # ### end Alembic commands ###
