"""sedikit menyesuikan ulang tabel

Revision ID: 5991714953dd
Revises: 563cf8fc7bf6
Create Date: 2025-09-14 16:19:04.522612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5991714953dd'
down_revision = '563cf8fc7bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CPPT', schema=None) as batch_op:
        batch_op.drop_column('perawat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CPPT', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perawat', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
