"""sedikit mengubah tabel pasien

Revision ID: 7f43347cc464
Revises: e7314b306023
Create Date: 2025-09-14 10:18:31.175092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f43347cc464'
down_revision = 'e7314b306023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasil_lab')
    op.drop_table('Laporan')
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cppt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'CPPT', ['cppt_id'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_rekam_medis', sa.String(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('patients_no_rm_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['no_rekam_medis'])
        batch_op.drop_column('no_rm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_rm', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('patients_no_rm_key'), ['no_rm'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('no_rekam_medis')

    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cppt_id')

    op.create_table('Laporan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tanggal', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('perawat', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('jabatan', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('subjective', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objective', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assessment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keterangan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dokter', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('Laporan_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Laporan_pkey'))
    )
    op.create_table('hasil_lab',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tanggal', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('hasil_lab_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hasil_lab_pkey'))
    )
    # ### end Alembic commands ###
