"""menghapus sedikit di tebal assement

Revision ID: e5257941b829
Revises: 7f43347cc464
Create Date: 2025-09-14 12:00:09.077845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5257941b829'
down_revision = '7f43347cc464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assesments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('assesments_patient_id_fkey'), type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assesment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'assesments', ['assesment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assesment_id')

    with op.batch_alter_table('assesments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('assesments_patient_id_fkey'), 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###
