"""Remove Embedding model

Revision ID: e7314b306023
Revises: 
Create Date: 2025-09-13 23:06:28.073426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7314b306023'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_perawat')
    op.drop_table('embeddings')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_rawat', sa.Enum('rawat_inap', 'rawat_jalan', name='status_rawat_enum'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'user', 'editor', name='roleenum'), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('role')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('status_rawat')

    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('embeddings_pkey'))
    )
    op.create_table('patient_perawat',
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('patient_perawat_patient_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('patient_perawat_user_id_fkey')),
    sa.PrimaryKeyConstraint('patient_id', 'user_id', name=op.f('patient_perawat_pkey'))
    )
    # ### end Alembic commands ###
